[package]
name = "verifier-client"
version = "0.1.0"
edition = "2021"

[dependencies]
sp1-zkvm = { workspace = true }

anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

# workspace
prover-executor-client = { workspace = true }
prover-primitives = { workspace = true }
